const courseEn = {
  brand: 'AC Academys',
  lastUpdate: '2026-02-08T16:31:00+0700',
  key: '2024-014-pixel-pioneers-nextjs-react-masterclass',
  locale: 'en',
  isActive: true,
  imageUrl: '/course/2024-014/poster/cover-image2.jpg',
  detailUrl:
    'https://dkscenter.gumon.io/en/course/2024-014-pixel-pioneers-nextjs-react-masterclass',
  title: 'Pixel Pioneers: Next.js and React Masterclass',
  code: '2024-014',
  duration: '2 Days, 09:00 - 17:00',
  overview:
    'Pixel Pioneers: Next.js and React Masterclass course is a learning experience focused on the basics of developing web applications using ReactJS, a JavaScript library used for building user interfaces. Participants will learn about the React structure, component creation, state management, API integration, and routing in web applications.',
  objectives: [
    'To provide participants with an understanding of the basics of ReactJS and web application development using React.',
    'To empower participants to create and manage various components in web applications using React.',
    'To enable participants to fetch data from APIs and manage the state of the application in the React framework.',
  ],
  whoShouldAttend: [
    'Software developers looking to learn about ReactJS and web application development.',
    'Developers with experience in website development who seek to understand the usage of ReactJS.',
    'Individuals interested in learning how to create efficient web applications using ReactJS.',
  ],
  prerequisites: [
    'Participants in the course should have basic knowledge of programming with JavaScript.',
    'Participants in the course should also have fundamental knowledge of web application development.',
    'Participants should have a basic understanding of HTML, CSS and JavaScript to better grasp the content.',
    'Preparation of necessary development tools such as Node.js and npm (Node Package Manager) for building and managing React projects.',
    'Ability to use Command Line Interface (CLI) for creating React projects and managing dependencies using npm.',
    'A computer equipped with programming tools such as a Text Editor or Integrated Development Environment (IDE) suitable for React development.',
    'Enthusiasm for learning and collaborating with others during the course. Working with team members helps participants gain valuable experience through knowledge exchange and collaboration.',
  ],
  participantsWillReceive: [
    'Training manuals/documentation.',
    'Lunch and refreshments.',
    'Certification upon completion of the Pixel Pioneers: Next.js and React Masterclass course.',
    'Excellent care and attention from instructors and staff.',
    'Unlimited attendance to the Pixel Pioneers: Next.js and React Masterclass course (limited to 5 repeat attendees per training session; if you wish to attend the workshop again, please contact our Facebook Page, Line, Email, or other channels to reserve your seat).',
    'If you are unable to attend the training session this time, you can reschedule your participation according to the training schedule.',
  ],
  outline: [
    { title: 'History of Web Frontend Development', descriptions: ['The evolution of web application development before the separation of Backend and Frontend.'] },
    { title: 'Pros and Cons', descriptions: ['Advantages and disadvantages of developing web applications with separated Backend and Frontend.'] },
    { title: 'System Architecture Overview', descriptions: ['An overview of current web application design with Backend and Frontend separation, including case studies.'] },
    { title: 'ECMAScript and TypeScript', descriptions: ['Modern JavaScript writing and fundamentals of TypeScript.'] },
    { title: 'What is React? And why Next.js?', descriptions: ['Introduction to React and React-powered frameworks.'] },
    { title: 'Workshop 1', descriptions: ['Creating a Next.js app.'] },
    { title: 'Project Structure', descriptions: ['Introduction to the basic structure of Next.js.'] },
    { title: 'HTML and JSX', descriptions: ['What is JSX?', 'Differences and precautions between HTML tags and JSX.'] },
    { title: 'Component Concept', descriptions: ['Explanation of functions and various necessary roles in developing web applications with React', 'Creating components to separate frequently used parts', 'Component exporting and importing', 'Passing values to components (Component Props).'] },
    { title: 'Workshop 2', descriptions: ['My First Component.'] },
    { title: 'Tailwind CSS', descriptions: ['Introduction to basic usage of Tailwind CSS'] },
    { title: 'Workshop 3', descriptions: ['My Home Page.'] },
    { title: "State: A Component's Memory", descriptions: ['Explanation of useState function and basic usage.'] },
    { title: 'Workshop 4', descriptions: ['Carousel banner.'] },
    { title: 'Reacting to Input with State', descriptions: ['Using State with Input.'] },
    { title: 'Workshop 5', descriptions: ['Search box.'] },
    { title: 'Sharing State Between Components', descriptions: ['Explanation of using State with other components.'] },
    { title: 'Workshop 6', descriptions: ['Search results.'] },
    { title: 'Next.js Routing', descriptions: ['Explanation of creating Route Paths in various formats', 'Page and Layout structures', 'page navigation (Linking and Navigating).'] },
    { title: 'Workshop 7', descriptions: ['New search page.'] },
    { title: 'Workshop 8', descriptions: ['Products and Details.'] },
    { title: 'Server Components and Client Components', descriptions: ['Explanation of differences and usage of Server Components and Client Components', 'Case studies.'] },
    { title: 'Next.js Data Fetching', descriptions: ['Explanation of API calls', 'Creating and using Server Actions and Mutations', 'Using formData and useFormStatus.'] },
    { title: 'Workshop 9', descriptions: ['Register.'] },
  ],
  publicSchedule: [
    {
      title: 'Pixel Pioneers: Next.js and React Masterclass - 1/2564',
      eventStart: '2024-10-07T09:00:00+0700',
      eventEnd: '2024-10-08T17:00:00+0700',
      saleStart: '2024-09-07T09:00:00+0700',
      saleEnd: '2024-10-06T21:00:00+0700',
      isActive: true,
      isSoldOut: false,
      deliveryMode: 'online',
      location: 'Online',
      scheduleKey: '2024-12-1',
    },
    {
      title: 'Pixel Pioneers: Next.js and React Masterclass - 2/2564',
      eventStart: '2024-11-02T09:00:00+0700',
      eventEnd: '2024-11-03T17:00:00+0700',
      saleStart: '2024-10-03T09:00:00+0700',
      saleEnd: '2024-11-01T21:00:00+0700',
      isActive: true,
      isSoldOut: false,
      deliveryMode: 'online',
      location: 'Online',
      scheduleKey: '2024-12-2',
    },
    {
      title: 'Pixel Pioneers: Next.js and React Masterclass - 3/2568',
      eventStart: '2025-07-26T09:00:00+0700',
      eventEnd: '2025-07-27T17:00:00+0700',
      saleStart: '2025-06-03T09:00:00+0700',
      saleEnd: '2025-07-25T21:00:00+0700',
      isActive: true,
      isSoldOut: false,
      location: 'COMING SOON',
      scheduleKey: '',
      ticketUrl: '',
    },
    {
      title: 'Pixel Pioneers: Next.js and React Masterclass - 1/2569',
      eventStart: '2026-02-21T09:00:00+0700',
      eventEnd: '2026-02-22T17:00:00+0700',
      saleStart: '2026-02-07T09:00:00+0700',
      saleEnd: '2026-02-20T21:00:00+0700',
      isActive: true,
      isSoldOut: false,
      location: 'Airport Rail Link Ladkrabang',
      scheduleKey: '',
      ticketUrl:
        'https://www.eventpop.me/e/100061-pixel-pioneers-nextjs-and-react-masterclass-1-2025',
    },
  ],
  documents: [],
};

export default courseEn;
