// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export type Course = {
  id?: string;
  lastUpdate: string;
  key: string;
  slug?: string;
  locale?: string;
  language?: string;
  isActive: boolean;
  defaultOrganizer?: NamedEntity | null;
  defaultOrganizers?: NamedEntity[];
  imageUrl?: string | null;
  detailUrl?: string | null;
  title: string;
  code: string;
  duration: string;
  overview: string;
  objectives: string[];
  audience?: string[];
  whoShouldAttend: string[];
  prerequisites: string[];
  participantsWillReceive: string[];
  outline: Outline[];
  curriculum?: Outline[];
  publicSchedule: PublicSchedule[];
  documents: Document[];
};

export type Document = {
  title: string;
  fileUrl: string;
};

export type Outline = {
  title: string;
  descriptions: string[];
};

export type NamedEntity = {
  name: string;
  url?: string;
};

export type Instructor = NamedEntity & {
  title?: string;
  profileUrl?: string;
};

export type PublicSchedule = {
  scheduleKey?: string;
  title: string;
  eventStart: string;
  eventEnd: string;
  ticketUrl?: null | string;
  saleStart?: null | string;
  saleEnd?: null | string;
  isActive: boolean;
  isSoldOut?: boolean;
  deliveryMode?: string;
  location?: string;
  locationUrl?: string;
  organizer?: NamedEntity | null;
  organizers?: NamedEntity[];
  instructors?: Instructor[];
};
