// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export type Course = {
  lastUpdate: string;
  key: string;
  isActive: boolean;
  imageUrl?: string | null;
  detailUrl?: string | null;
  title: string;
  code: string;
  duration: string;
  overview: string;
  objectives: string[];
  whoShouldAttend: string[];
  prerequisites: string[];
  participantsWillReceive: string[];
  outline: Outline[];
  publicSchedule: PublicSchedule[];
  documents: Document[];

}

export type Document = {
  title: string;
  fileUrl: string;
}

export type Outline = {
  title: string;
  descriptions: string[];
}

export type PublicSchedule = {
  title: string;
  eventStart: string;
  eventEnd: string;
  ticketUrl?: null | string;
  saleStart?: null | string;
  saleEnd?: null | string;
  isActive: boolean;
  isSoldOut?: boolean;
  location?: string;
}