const courseTh = {
  lastUpdate: '2024-02-19T09:00:00+0700',
  key: '2024-007-modern-web-frontend-with-react',
  locale: 'th',
  isActive: true,
  imageUrl: '/course/2024-007/poster/cover-image2-01-01.png',
  detailUrl:
    'https://dkscenter.gumon.io/course/2024-007-modern-web-frontend-with-react',
  title: 'Modern Web Frontend with React (Next.js - App Router - Typescript)',
  code: '2024-007',
  duration: '2 วัน, 09:00 - 17:00',
  overview:
    'คอร์ส Modern Web Frontend with React (Next.js - App Router - Typescript) เป็นการเรียนรู้เกี่ยวกับพื้นฐานของการพัฒนาเว็บแอปพลิเคชันด้วย ReactJS ซึ่งเป็นไลบรารี JavaScript ที่ใช้สำหรับสร้าง UI และอินเทอร์เฟซผู้ใช้ ผู้เรียนจะได้เรียนรู้เกี่ยวกับโครงสร้างของ React, การสร้างคอมโพเนนต์, การจัดการสถานะ, การเรียกใช้ API, และการทำ routing ในเว็บแอปพลิเคชัน',
  objectives: [
    'เพื่อให้ผู้เรียนมีความเข้าใจเกี่ยวกับพื้นฐานของ ReactJS และการพัฒนาเว็บแอปพลิเคชันด้วย React',
    'เพื่อให้ผู้เรียนสามารถสร้างและจัดการกับคอมโพเนนต์ต่าง ๆ ในเว็บแอปพลิเคชันด้วย React',
    'เพื่อให้ผู้เรียนสามารถเรียกใช้งานข้อมูลจาก API และจัดการกับสถานะของแอปพลิเคชันในรูปแบบของ React',
  ],
  whoShouldAttend: [
    'นักพัฒนาซอฟต์แวร์ที่ต้องการเรียนรู้เกี่ยวกับ ReactJS และการพัฒนาเว็บแอปพลิเคชัน',
    'นักพัฒนาที่มีประสบการณ์ในการพัฒนาเว็บไซต์และต้องการทำความเข้าใจในการใช้ ReactJS',
    'ผู้ที่สนใจเรียนรู้เกี่ยวกับการสร้างเว็บแอปพลิเคชันที่มีประสิทธิภาพด้วย ReactJS',
  ],
  prerequisites: [
    'ผู้เข้าร่วมคอร์สควรมีความรู้พื้นฐานเกี่ยวกับการเขียนโปรแกรมด้วยภาษา JavaScript',
    'ผู้เข้าร่วมคอร์สควรความรู้พื้นฐานเกี่ยวกับการพัฒนาเว็บแอปพลิเคชัน',
    'ผู้เข้าร่วมคอร์สควรมีความรู้พื้นฐานเกี่ยวกับ HTML, CSS และ JavaScript เพื่อให้เข้าใจเนื้อหาได้ดียิ่งขึ้น',
    'การเตรียมโปรแกรมพัฒนาที่จำเป็น เช่น Node.js และ npm (Node Package Manager) เพื่อใช้ในการสร้างและจัดการโปรเจค React',
    'การมีความสามารถในการใช้งาน Command Line Interface (CLI) เพื่อการสร้างโปรเจค React และการจัดการกับ dependencies ต่าง ๆ โดยใช้ npm',
    'คอมพิวเตอร์ที่มีเครื่องมือสำหรับการเขียนโปรแกรมเช่นโปรแกรม Text Editor หรือ Integrated Development Environment (IDE) ที่เหมาะสมสำหรับการพัฒนา React',
    'ความกระตือรือร้นในการเรียนรู้และการทำงานร่วมกับผู้อื่นในระหว่างการศึกษา การทำงานร่วมกับสมาชิกในทีมช่วยให้ผู้เรียนได้รับประสบการณ์ที่มีประโยชน์จากการแลกเปลี่ยนความรู้และประสบการณ์',
  ],
  participantsWillReceive: [
    'เอกสารคู่มือการอบรม',
    'อาหารกลางวันและอาหารว่าง',
    'ใบรับรองผ่านการอบรมหลักสูตร Modern Web Frontend with React (Next.js - App Router - Typescript)',
    'การดูแลเอาใจใส่เป็นอย่างดีจากวิทยากรและทีมงาน Staff',
    'สามารถเข้าร่วม Modern Web Frontend with React (Next.js - App Router - Typescript) ซ้ำได้ไม่จำกัดจำนวนครั้ง (จำกัดสิทธิ์เข้าร่วมซ้ำ 5 ท่านต่อรอบการอบรม หากท่านต้องการเข้าร่วม Workshop ซ้ำ กรุณาติดต่อ Facebook Page, Line, Email หรือช่องทางอื่น ๆ เพื่อสำรองที่นั่ง)',
    'หากท่านไม่สะดวกเข้าร่วมการอบรมในครั้งนี้ ท่านสามารถเลื่อนการเข้าร่วมอบรมได้ตามตารางการอบรม',
  ],
  outline: [
    { title: 'History of Web Frontend Development', descriptions: ['ประวัติศาสตร์ของการพัฒนาเว็บแอปพลิเคชันก่อนจะมีการพัฒนาแบบแยกระหว่าง Backend และ Frontend'] },
    { title: 'Pros and Cons', descriptions: ['ข้อดี ข้อเสีย ของการพัฒนาเว็บแอปพลิเคชันแบบแยก Backend และ Frontend'] },
    { title: 'System Architecture Overview', descriptions: ['ภาพรวมของการออกแบบเว็บแอปพลิเคชันแบบแยก Backend และ Frontend ในปัจจุบัน พร้อมกรณีศึกษา'] },
    { title: 'ECMAScript and TypeScript', descriptions: ['การเขียนจาวาสคริปต์สมัยใหม่ และพื้นฐานการเขียน Typescript'] },
    { title: 'What is React? And why Next.js?', descriptions: ['ทำความรู้จักกับ React และ React-powered frameworks'] },
    { title: 'Workshop 1', descriptions: ['Creating a Next.js app.'] },
    { title: 'Project Structure', descriptions: ['แนะนำโครงสร้างของ Next.js'] },
    { title: 'HTML and JSX', descriptions: ['JSX คืออะไร?', 'ความแตกต่างและข้อควรระวังระหว่าง Html tag และ JSX'] },
    { title: 'Component Concept', descriptions: ['อธิบายฟังก์ชันและหน้าที่ต่าง ๆ ที่จำเป็นต่อการพัฒนาเว็บแอปพลิเคชันด้วย React', 'การสร้าง Component เพื่อแยกส่วนประกอบที่ใช้งานบ่อย ๆ', 'การ Export และ Import ส่วนประกอบเข้ามาใช้งาน', 'การส่งค่าไปยังส่วนประกอบ (Component Pops)'] },
    { title: 'Workshop 2', descriptions: ['My First Component.'] },
    { title: 'Tailwind CSS', descriptions: ['แนะนำการใช้งาน Tailwind CSS เบื้องต้น'] },
    { title: 'Workshop 3', descriptions: ['My Home Page.'] },
    { title: "State: A Component's Memory", descriptions: ['อธิบายฟังก์ชัน useState และวิธีการใช้งานเบื้องต้น'] },
    { title: 'Workshop 4', descriptions: ['Carousel banner.'] },
    { title: 'Reacting to Input with State', descriptions: ['การใช้งาน State ร่วมกับ Input'] },
    { title: 'Workshop 5', descriptions: ['Search box.'] },
    { title: 'Sharing State Between Components', descriptions: ['อธิบายการใช้ State ร่วมกับ Component อื่นๆ'] },
    { title: 'Workshop 6', descriptions: ['Search results.'] },
    { title: 'Next.js Routing', descriptions: ['อธิบายการสร้าง Route Path ในรูปแบบต่าง ๆ', 'โครงสร้างของ Page และ Layouts', 'การเปลี่ยนหน้า (Linking and Navigating)'] },
    { title: 'Workshop 7', descriptions: ['New search page.'] },
    { title: 'Workshop 8', descriptions: ['Products and Details.'] },
    { title: 'Server Components and Client Components', descriptions: ['อธิบายข้อแตกต่างและการใช้งาน Server Components และ Client Components', 'กรณีศึกษา'] },
    { title: 'Next.js Data Fetching', descriptions: ['อธิบายการเรียกใช้ API', 'การสร้างและเรียกใช้งาน Server Actions and Mutations', 'การใช้งาน formData และ useFormStatus'] },
    { title: 'Workshop 9', descriptions: ['Register.'] },
    { title: 'Authentication Flow', descriptions: ['อธิบายการวางโครงสร้างและหลักการของระบบยืนยันตัวตน (Authentication)'] },
    { title: 'Workshop 10', descriptions: ['Login.'] },
    { title: 'Passing Data Deeply with Context', descriptions: ['อธิบายหลักการ ความจำเป็น และวิธิการบริหารจัดการข้อมูลที่มีความซับซ้อน', 'กรณีศึกษา'] },
    { title: 'Workshop 11', descriptions: ['My Profile.'] },
    { title: 'Error Handling and Middleware', descriptions: ['อธิการหลักการทำ Error Handling ในแบบฉบับของ Next.js และ การทำงานของ Middleware', 'กรณีศึกษา'] },
    { title: 'Workshop 12', descriptions: ['Redirect when not logged in.'] },
    { title: 'Scaling Up with Reducer and Context', descriptions: ['อธิบายการใช้ Reducer และ State Action ร่วมกับ Context', 'กรณีศึกษา'] },
    { title: 'Workshop 13', descriptions: ['Add products to cart.'] },
    { title: 'Synchronizing with Effects', descriptions: ['อธิบายการทำงานของฟังก์ชัน useEffect และวิธีการใช้งานในรูปแบบต่าง ๆ'] },
    { title: 'Workshop 14', descriptions: ['Checkout!'] },
    { title: 'Workshop 15', descriptions: ['Order History.'] },
    { title: 'Environment Variables and Deploying', descriptions: ['อธิบายการใช้งาน Environment Variables และการ Deploy ในรูปแบบต่าง ๆ'] },
    { title: 'Workshop 16', descriptions: ['Hello World!'] },
  ],
  publicSchedule: [
    {
      title: 'Modern Web Frontend with React - 1/2024',
      eventStart: '2024-05-25T09:00:00+0700',
      eventEnd: '2024-05-26T17:00:00+0700',
      ticketUrl: 'https://www.eventpop.me/e/21610/modern-web-frontend-with-react-1-2024',
      saleStart: '2024-03-21T09:00:00+0700',
      saleEnd: '2024-05-24T23:59:59+0700',
      isActive: true,
      isSoldOut: false,
      location: 'BTS Phaya Thai',
      scheduleKey: '2024-1',
    },
    {
      title: 'Modern Web Frontend with React - 2/2024',
      eventStart: '2024-07-16T09:00:00+0700',
      eventEnd: '2024-07-17T17:00:00+0700',
      ticketUrl: '',
      saleStart: '2024-06-15T09:00:00+0700',
      saleEnd: '2024-07-15T23:59:59+0700',
      isActive: true,
      isSoldOut: false,
      location: 'BTS Phaya Thai',
      scheduleKey: '2024-2',
    },
    {
      title: 'Modern Web Frontend with React - 3/2024',
      eventStart: '2024-09-14T09:00:00+0700',
      eventEnd: '2024-09-15T17:00:00+0700',
      ticketUrl: '',
      saleStart: '2024-08-13T09:00:00+0700',
      saleEnd: '2024-09-13T23:59:59+0700',
      isActive: true,
      isSoldOut: false,
      location: 'BTS Phaya Thai',
      scheduleKey: '2024-3',
    },
  ],
  documents: [
    {
      title: 'Modern Web Frontend with React (Next.js - App Router - Typescript) (English Version)',
      fileUrl: '/course/2024-007/document/modern-web-frontend-with-react-en.pdf',
    },
    {
      title: 'Modern Web Frontend with React (Next.js - App Router - Typescript) (Thai Version)',
      fileUrl: '/course/2024-007/document/modern-web-frontend-with-react-th.pdf',
    },
  ],
};

export default courseTh;
